import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {root,config,selectLecture,loadLecture,validateDeck,validateSources,isApproved,contentDigest,sha,sanitizeDeck} from '../scripts/lib.mjs';

const dir=selectLecture('01-agent-ai-intro'),original=loadLecture(dir);
const mutate=fn=>{const x=structuredClone(original);x.brief=original.brief;x.dir=original.dir;fn(x);return validateDeck(x)};
test('실제 1회차는 입력 해시, 요구 범위, 장수, 시간이 일치한다',()=>assert.deepEqual(validateDeck(original),[]));
test('중복 slide ID와 없는 출처는 실패한다',()=>{const e=mutate(x=>{x.deck.slides[1].id=x.deck.slides[0].id;x.deck.slides[4].sourceIds=['SRC-NOT-FOUND']});assert.ok(e.some(x=>x.includes('중복')));assert.ok(e.some(x=>x.includes('없는 source ID')))});
test('오래된 brief 해시는 실패한다',()=>assert.ok(mutate(x=>x.deck.inputDigest='0'.repeat(64)).some(x=>x.includes('inputDigest'))));
test('요구 주제와 본편 시간 합계 누락은 실패한다',()=>{const e=mutate(x=>{for(const s of x.deck.slides)s.requirementIds=s.requirementIds.filter(i=>i!=='REQ-MCP');x.deck.slides[0].durationSec=1});assert.ok(e.some(x=>x.includes('REQ-MCP')));assert.ok(e.some(x=>x.includes('본편 시간 합계')))});
test('고정 질의응답 0분, 영상 단일 합산, 유동 여유 계산이 일치한다',()=>{assert.equal(original.deck.questionsSec,0);assert.equal(original.deck.questionsMode,'flexible');assert.equal(original.deck.slides.find(s=>s.kind==='qa').durationSec,0);assert.equal(original.deck.plannedMainDurationSec,3289);assert.equal(original.deck.plannedSpeakerDurationSec,2280);assert.equal(original.deck.actualVideoDurationSec,1009);assert.equal(original.deck.flexibleBufferSec,311);assert.equal(original.deck.estimatedFullDurationSec,3289)});
test('60분 상한 초과를 검출하고 회차별 다른 전체 시간은 허용한다',()=>{const over=mutate(x=>{x.deck.slides.find(s=>s.id==='L01-S01').durationSec+=312});assert.ok(over.some(x=>x.includes('수업 상한 초과')));const x=structuredClone(original);x.brief=Buffer.from(original.brief.toString().replace('duration_minutes: 60','duration_minutes: 70'));x.dir=original.dir;x.deck.sessionDurationSec=4200;x.deck.flexibleBufferSec=911;x.deck.inputDigest=sha(x.brief);assert.deepEqual(validateDeck(x),[])});
test('향후 회차의 기본 화면·대본 언어는 한국어다',()=>{assert.equal(config.slideLanguage,'ko');assert.equal(config.scriptLanguage,'ko');assert.match(fs.readFileSync(path.join(root,'scripts/cli.mjs'),'utf8'),/slide_language: \$\{config\.slideLanguage\}[\s\S]*script_language: \$\{config\.scriptLanguage\}/)});
test('사용자 YouTube 썸네일은 비공개 빌드에만 포함된다',()=>{const assets=original.assets.assets.filter(a=>a.id.startsWith('thumb-v'));assert.equal(assets.length,3);assert.ok(assets.every(a=>a.publicAllowed===false&&a.rightsStatus==='rights_unverified'&&a.sourcePath.startsWith('.private/')));assert.equal(sanitizeDeck(original.deck,original.assets.assets).assets.some(a=>a.id.startsWith('thumb-v')),false);assert.equal(sanitizeDeck(original.deck,original.assets.assets,{includePrivateAssets:true}).assets.filter(a=>a.id.startsWith('thumb-v')).length,3)});
test('비공개 썸네일 원본은 CI 체크아웃에 없어도 검증되며 공개 승인 해시에 포함되지 않는다',()=>{const x=structuredClone(original);x.brief=original.brief;x.dir=original.dir;x.assets=structuredClone(original.assets);for(const a of x.assets.assets.filter(a=>a.id.startsWith('thumb-v')))a.sourcePath='.private/lecture-assets/CI_MISSING/'+path.basename(a.sourcePath);assert.deepEqual(validateDeck(x),[]);assert.equal(contentDigest(original),contentDigest({...original,assets:{...original.assets,assets:original.assets.assets.filter(a=>a.publicAllowed===true)}}))});
test('0×0 또는 NaN 차트와 경로 탈출 자산은 실패한다',()=>{const e=mutate(x=>{x.deck.slides[2].blocks.push({type:'chart',data:{labels:['x'],values:[NaN]}});x.assets.assets=[{id:'BAD',path:'../private.png'}]});assert.ok(e.some(x=>x.includes('chart 데이터')));assert.ok(e.some(x=>x.includes('자산 경로 탈출')))});
test('승인 해시는 콘텐츠 변경 후 무효가 된다',()=>{const d=contentDigest(original),x=structuredClone(original);x.brief=original.brief;x.dir=original.dir;x.approval={status:'approved',approvedContentDigest:d,scope:{site:true}};assert.equal(isApproved(x),true);x.approval.approvedContentDigest=sha('stale');assert.equal(isApproved(x),false)});
test('출처 URL과 확인일 오류를 검출하고 접근 응답과 내용 검증을 구분한다',()=>{const x=structuredClone(original.sources);x.sources[0].url='javascript:alert(1)';x.sources[1].checked_at='2026-02-30';const result=validateSources(x,'2026-09-25');assert.ok(result.errors.some(e=>e.includes('HTTP URL')));assert.ok(result.errors.some(e=>e.includes('확인일 오류')));assert.ok(result.warnings.some(e=>e.includes('본문 검증 필요')))});
test('승인된 공개 빌드는 슬라이드만 포함하고 비공개 썸네일과 발표자 원고를 제외한다',()=>{
 execFileSync('npm',['run','build:public'],{cwd:root,stdio:'pipe'});
 const publicDir=path.join(root,'dist','public'),slug='01-agent-ai-intro';
 const txt=fs.readFileSync(path.join(publicDir,'portfolio.json'),'utf8');
 assert.deepEqual(JSON.parse(txt).cards.map(x=>x.slug),[slug]);
 const deckPath=path.join(publicDir,'lectures',slug,'deck.json');
 assert.equal(fs.existsSync(deckPath),true);
 const deckText=fs.readFileSync(deckPath,'utf8');
 assert.equal(deckText.includes('speakerNotes'),false);
 assert.equal(JSON.parse(deckText).assets.some(a=>a.id.startsWith('thumb-v')),false);
 assert.equal(fs.existsSync(path.join(publicDir,'lectures',slug,'assets','user')),false);
 assert.equal(fs.existsSync(path.join(publicDir,'lectures',slug,'presenter.html')),false);
 assert.equal(fs.existsSync(path.join(publicDir,'lectures',slug,'presenter-deck.json')),false);
 assert.equal(txt.includes('PRIVATE_TEST_SENTINEL_DO_NOT_PUBLISH'),false);
 execFileSync('npm',['run','release:check'],{cwd:root,stdio:'pipe'});
});
